services:
  server:
    image: spring_http_remoting_server_java11:25.1.2
    ports:
      - 8080:8080
    networks:
      - oracle_db_net
    container_name: spring_http_remoting_server_java11

networks:
  oracle_db_net:
    name: oracle_db_network
    external: true
