services:
  server:
    image: java_ee_factoryapi_server_java11:25.1.2
    ports:
      - 14235:8080
    environment:
      - db.username=dbw_examples
      - db.password=dbw_examples
      - db.host=oracle_db
    networks:
      - oracle_db_net
    container_name: java_ee_factoryapi_server_java11
      
networks:
  oracle_db_net:
    name: oracle_db_network
    external: true
